### PR TITLE
Upgrading for Craft 4.0

### PR DESCRIPTION
**Pull request by davidwebca**
So far, most of the changes I've seen are functions being renamed and type hints missing, otherwise with the changes I've just made to this, I'm able to get to the tags in the admin panel without triggering any warning or error. Feel free to review o tag this as a new beta version to ease people's upgrading!

### CODE REVIEW

**Comment by MarcusGaius** [comment]
Any updates?

**Comment by jesuismaxime** [comment]
@davidwebca it seems to not working well Craft CMS v4.0.3 or Craft CMS v4.1.0.2. 
- Tags indexes are empty (but the elementCount is right) 
- Field label' fieldLayout overrides aren't displayed in the "edit" template 

But both seems to be related with deeper Craft compatibility. I will try to look into it this weekend! GJ!

**Comment by davidwebca** [comment]
Salut Max! Comme on se croise 🤘😏 

Can you let me know what you mean by Tags indexes? Just making sure since lots of people use "index" to mean different things. Do you mean the [search indexes](https://craftcms.com/docs/4.x/searching.html#configuring-custom-fields-for-search)? Or the ability to sort by [different columns](https://github.com/verbb/element-index-defaults) in the admin?

And you're absolutely right for the field layout overrides. Hadn't noticed since I rarely use it. Will check!

> @davidwebca it seems to not working well Craft CMS v4.0.3 or Craft CMS v4.1.0.2.
> 
> * Tags indexes are empty (but the elementCount is right)
> * Field label' fieldLayout overrides aren't displayed in the "edit" template
> 
> But both seems to be related with deeper Craft compatibility. I will try to look into it this weekend! GJ!

**Comment by jesuismaxime** [comment]
The moment when you update all the plugins on a project (not related to TagManager (ex. Neo, Supertable) and the bug isn't there.

Earlier, the list (the [Index Page](https://craftcms.com/docs/3.x/extend/element-types.html#index-page) concept in Craft) was empty (even with a clean start or emptied caches), but the count was correct ("1-3 of 3 elements").

**Comment by socceroos** [comment]
What is the progress on this PR? Is it ready to merge?

**Comment by gbowne-quickbase** [comment]
Any update on this? We'd love to have it included in our 4.x installation

**Pull request merged**
